In [2]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
x = torch.arange(3, dtype = torch.float32)
x

tensor([0., 1., 2.])

In [4]:
len(x)

3

Matrices

In [5]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [6]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

Tensors

In [7]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [8]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of `A` to `B` by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

Hadamard Product

In [9]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [10]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X)

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

Reduction

In [11]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [12]:
A.shape, A.sum(axis=0)

(torch.Size([2, 3]), tensor([3., 5., 7.]))

In [13]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [14]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

Non-Reduction Sum

In [15]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [16]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [17]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

Dot Products

In [18]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [19]:
torch.sum(x * y)

tensor(3.)

Matrix-Vector Products

In [20]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

Matrix-Matrix Multiplication

In [21]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

Norms

In [22]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [23]:
torch.abs(u).sum()

tensor(7.)

EXERCISES

1. Prove that the transpose of the transpose of a matrix is the matrix itself: $(A^\intercal)^\intercal = A$



The (i,j)-entry of AT is the (j,i)-entry of A, so the (i,j)-entry of (AT)T is the (j,i)-entry of AT, which is the (i,j)-entry of A. Thus all entries of (AT)T coincide with the corresponding entries of A, so these two matrices are equal.

2. Given two matrices $\mathbf{A}$ and $\mathbf{B}$, show that sum and transposition commute:
$\mathbf{A}^\intercal + \mathbf{B}^\intercal = (\mathbf{A} + \mathbf{B})^\intercal$

The (i,j)-entry of AT+BT is the sum of (i,j)-entries of AT and BT, which are (j,i)-entries of A and B, respectively. Thus the (i,j)-entry of AT+BT is the (j,i)-entry of the sum of A and B, which is equal to the (i,j)-entry of the transpose (A+B)T.

3. Given any square matrix $\mathbf{A}$, is $\mathbf{A} + \mathbf{A}^\intercal$ always symmetric? Can you prove the result by using only the result of the previous two exercises?

\begin{align*}
    (\mathbf{A} + \mathbf{A}^\intercal)^\intercal &= \mathbf{A}^\intercal + (\mathbf{A}^\intercal)^\intercal \\
    &= \mathbf{A}^\intercal + A \\
    &= \mathbf{A} + \mathbf{A}^\intercal
\end{align*}

3. We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)? Write your answer without implementing any code, then check your answer using code.

In [28]:
len(X)

2

5. For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?