In [57]:
import torch

x = torch.arange(4.0, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [58]:
x.requires_grad_(True)
id(x)

1951679645872

In [59]:
y = 2*x@x
y

tensor(28., grad_fn=<DotBackward0>)

In [60]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [61]:
x.grad == 4*x

tensor([True, True, True, True])

In [63]:
x.grad.zero_()
y = x.sum()
y.backward()
x.sum()

tensor(6., grad_fn=<SumBackward0>)

Backward for Non-Scalar Variables

In [69]:
x.grad.zero_()
y = x * x
y.backward(gradient=torch.ones(len(y)))  # Faster: y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])